services:
  - type: web
    name: cartivo-ecommerce
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir ecom ecom.wsgi:application"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
