# Generated by Django 5.2 on 2026-09-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_location',
            field=models.CharField(blank=True, default='', help_text='Current physical checkpoint location of the shipment', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.CharField(blank=True, default='Cartivo Express Delivery', help_text='Designated logistics carrier', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.CharField(blank=True, default='', help_text='Target delivery window / SLA', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', help_text='Courier parcel tracking number', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing & Packed'), ('SHIPPED', 'Dispatched / In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=30),
        ),
    ]
