# Generated by Django 5.2 on 2026-09-19 05:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_current_location_order_delivery_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing & Packed'), ('SHIPPED', 'Dispatched / In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=30)),
                ('location', models.CharField(help_text='Physical facility, hub, or city of checkpoint', max_length=200)),
                ('notes', models.CharField(blank=True, default='', help_text='Event description or courier notes', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='orders.order')),
            ],
            options={
                'verbose_name': 'Delivery Checkpoint',
                'verbose_name_plural': 'Delivery Checkpoints',
                'ordering': ['-timestamp'],
            },
        ),
    ]
