# Generated by Django 5.2 on 2026-09-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_deliverycheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycheckpoint',
            name='is_customer_visible',
            field=models.BooleanField(default=True, help_text='Whether this checkpoint is customer visible'),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_collected_by',
            field=models.CharField(blank=True, default='', help_text='Staff or courier agent who collected cash', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual cash collected', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when order was delivered', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of delivery attempts made'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_failure_reason',
            field=models.CharField(blank=True, default='', help_text='Internal failure reason if delivery fails', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, default='', help_text='Internal operational notes not visible to customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, default='', help_text='Public courier parcel tracking link', max_length=500),
        ),
        migrations.AlterField(
            model_name='deliverycheckpoint',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing & Packed'), ('READY_TO_PACK', 'Ready to Pack'), ('PACKED', 'Packed'), ('READY_TO_SHIP', 'Ready to Ship'), ('SHIPPED', 'Dispatched / In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing & Packed'), ('READY_TO_PACK', 'Ready to Pack'), ('PACKED', 'Packed'), ('READY_TO_SHIP', 'Ready to Ship'), ('SHIPPED', 'Dispatched / In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=30),
        ),
    ]
