# Generated by Django 5.2 on 2026-09-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliverycheckpoint_is_customer_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('RAZORPAY', 'Razorpay (Online Payment)'), ('UPI', 'Unified Payments Interface (UPI)'), ('CARD', 'Credit / Debit Card'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Digital Wallet')], db_index=True, default='COD', max_length=30),
        ),
    ]
