# Generated by Django 5.2 on 2026-09-19 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_deliverycheckpoint_is_customer_visible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_PACKED', 'Order Packed'), ('ORDER_SHIPPED', 'Order Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('ORDER_DELIVERED', 'Order Delivered'), ('COD_PAYMENT_RECEIVED', 'COD Payment Received'), ('ORDER_COMPLETED', 'Order Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('ORDER_RETURNED', 'Order Returned'), ('ORDER_CANCELLED', 'Order Cancelled')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
