# Generated by Django 5.2 on 2026-09-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal label (e.g. 'Homepage Trending Section')", max_length=120)),
                ('section_type', models.CharField(choices=[('category_bar', 'Category Sub-Menu Bar'), ('hero_banners', 'Promotional Marquee Carousel Banners'), ('trust_bar', 'Value Propositions / Trust Bar'), ('curated_categories', 'Curated Categories Grid'), ('product_grid', 'Product Grid Section (Trending / Featured / New)'), ('newsletter', 'VIP Newsletter Subscription Block'), ('custom_html', 'Custom HTML Block')], db_index=True, max_length=40)),
                ('title', models.CharField(blank=True, help_text="Section headline, e.g. 'Trending This Week'", max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text="Section tag/kicker, e.g. 'Handpicked Pieces'", max_length=150)),
                ('view_all_url', models.CharField(blank=True, default='/products/', max_length=255)),
                ('view_all_text', models.CharField(blank=True, default='Explore All', max_length=60)),
                ('product_filter_type', models.CharField(choices=[('trending', 'Trending Products'), ('featured', 'Featured Products'), ('new_arrivals', 'New Arrivals (Latest Added)'), ('manual', 'Manual Product Selection')], default='trending', help_text='How products should be selected if section_type is product_grid', max_length=30)),
                ('max_items', models.PositiveIntegerField(default=4, help_text='Maximum products to display')),
                ('custom_content', models.TextField(blank=True, help_text='HTML snippet if custom_html section type is chosen')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls top-to-bottom rendering order on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Headline, e.g. 'VIRAT V1 5G'", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text="e.g. 'CARTIVO | Exclusive'", max_length=200)),
                ('price_tag', models.CharField(blank=True, help_text="e.g. 'From ₹14,499' or 'Under ₹499'", max_length=100)),
                ('description', models.TextField(blank=True, help_text="e.g. 'Now with 128 GB storage'")),
                ('badge_text', models.CharField(blank=True, help_text="e.g. 'BIG BACHAT DAYS'", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback CDN image URL', max_length=500)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('mobile_image_url', models.URLField(blank=True, max_length=500)),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=60)),
                ('button_url', models.CharField(blank=True, default='/products/', max_length=255)),
                ('bg_gradient', models.CharField(default='from-neutral-950 via-slate-900 to-neutral-950', help_text='Tailwind gradient classes for background card styling', max_length=255)),
                ('border_color', models.CharField(blank=True, default='border-slate-800/80', help_text='Tailwind border class', max_length=100)),
                ('text_color_theme', models.CharField(choices=[('dark', 'Dark Card / Light Text'), ('light', 'Light Card / Dark Text')], default='dark', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional scheduling start time (UTC). If set, banner will only appear on or after this time.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional scheduling end time (UTC). If set, banner will expire after this time.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('icon_name', models.CharField(default='truck', help_text="Lucide icon name (e.g. 'truck', 'shield-check', 'rotate-ccw', 'headphones')", max_length=60)),
                ('color_theme', models.CharField(default='blue', help_text="Theme name ('blue', 'emerald', 'amber', 'purple')", max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trust Badge / Value Proposition',
                'verbose_name_plural': 'Trust Badges / Value Propositions',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('custom_url', models.CharField(blank=True, help_text='Custom URL override. If blank and category is selected, uses category URL.', max_length=255)),
                ('icon_name', models.CharField(default='sparkles', help_text="Lucide icon name (e.g., 'sparkles', 'shirt', 'smartphone', 'laptop', 'sparkle', 'lamp', 'tv', 'smile', 'utensils', 'shield', 'activity', 'armchair', 'book-open', 'bike')", max_length=60)),
                ('is_highlighted', models.BooleanField(default=False, help_text="Apply active highlight styling (e.g. 'For You' item)")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional linked catalog category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_nav_items', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Category Sub-Nav Item',
                'verbose_name_plural': 'Category Sub-Nav Items',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, help_text='Optional override for card title', max_length=120)),
                ('custom_subtitle', models.CharField(blank=True, help_text="e.g. 'Headphones, speakers & drivers'", max_length=200)),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='homepage/categories/')),
                ('custom_image_url', models.URLField(blank=True, help_text='Fallback card image URL', max_length=500)),
                ('badge_text', models.CharField(blank=True, help_text="e.g. '18 Products'", max_length=60)),
                ('badge_color', models.CharField(blank=True, default='blue', help_text="e.g. 'blue', 'amber', 'emerald', 'purple'", max_length=30)),
                ('link_url', models.CharField(blank=True, help_text='Override target URL', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_curations', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Homepage Category Showcase',
                'verbose_name_plural': 'Homepage Category Showcases',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', help_text="Relative URL (e.g., '/products/') or absolute URL (e.g., 'https://...')", max_length=255)),
                ('badge_text', models.CharField(blank=True, help_text="Optional highlight badge text, e.g. '20%', 'Hot', 'New'", max_length=30)),
                ('badge_color', models.CharField(blank=True, default='amber', help_text="Color identifier, e.g. 'amber', 'blue', 'rose', 'emerald'", max_length=30)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for top-level navbar items. Select a parent to create a dropdown child item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.navbaritem')),
            ],
            options={
                'verbose_name': 'Navbar Item',
                'verbose_name_plural': 'Navbar Items',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_section_assignments', to='catalog.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_products', to='cms.homepagesection')),
            ],
            options={
                'verbose_name': 'Section Product',
                'verbose_name_plural': 'Section Products',
                'ordering': ['display_order', 'id'],
                'unique_together': {('section', 'product')},
            },
        ),
    ]
