# Generated by Django 5.2 on 2026-09-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynavitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload category icon/image saved to media storage', null=True, upload_to='category_nav/'),
        ),
        migrations.AddField(
            model_name='categorynavitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g. Google image, CDN)', max_length=500),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload section banner/image saved to media storage', null=True, upload_to='sections/'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='image_url',
            field=models.URLField(blank=True, help_text='External or Google image URL', max_length=500),
        ),
    ]
