# Generated by Django 5.2 on 2026-09-17 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_attribute_producttag_product_cost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g. 'A-01', 'RACK-3B', 'DAMAGED'", max_length=50)),
                ('name', models.CharField(blank=True, help_text='Optional human-readable label', max_length=100)),
                ('location_type', models.CharField(choices=[('STORAGE', 'Storage Bin / Shelf'), ('RECEIVING', 'Receiving Dock'), ('PICKING', 'Fast-Pick Area'), ('DISPATCH', 'Outbound Dispatch'), ('DAMAGED', 'Damaged / Hold Bay'), ('DEFAULT', 'General Warehouse Area')], default='STORAGE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_quantity', models.PositiveIntegerField(default=0, help_text='Physical count currently stored in warehouse')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Units promised to pending orders or checkout holds')),
                ('incoming_quantity', models.PositiveIntegerField(default=0, help_text='Units in transit from suppliers or transfer orders')),
                ('reorder_point', models.PositiveIntegerField(default=10, help_text='Threshold quantity to trigger LOW_STOCK status and replenishment alerts')),
                ('safety_stock', models.PositiveIntegerField(default=5, help_text='Buffer stock to prevent stockouts from demand spikes')),
                ('maximum_stock', models.PositiveIntegerField(default=1000, help_text='Maximum capacity threshold before flagging OVERSTOCK')),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('OVERSTOCK', 'Overstock')], db_index=True, default='OUT_OF_STOCK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_records', to='inventory.location')),
                ('product', models.ForeignKey(help_text='Underlying Catalog Product', on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Optional specific variant combination', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Records',
                'ordering': ['warehouse', 'product', 'variant'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('INCREASE', 'Increase On-Hand (+Qty)'), ('DECREASE', 'Decrease On-Hand (-Qty)'), ('SET', 'Set Absolute Count (=Qty)')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity delta or absolute target count')),
                ('previous_on_hand', models.IntegerField()),
                ('new_on_hand', models.IntegerField()),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged Goods'), ('LOST', 'Lost / Shrinkage'), ('FOUND', 'Found / Extra Discovered'), ('COUNTING_ERROR', 'Physical Counting Discrepancy'), ('OPENING_STOCK', 'Initial Opening Stock'), ('MANUAL_CORRECTION', 'Managerial Correction'), ('OTHER', 'Other / Custom Justification')], max_length=40)),
                ('notes', models.TextField(blank=True, help_text='Audit explanation for this adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units held')),
                ('reference_type', models.CharField(db_index=True, default='ORDER', max_length=50)),
                ('reference_id', models.CharField(db_index=True, help_text='Order number or Cart session ID', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Active Hold)'), ('FULFILLED', 'Fulfilled (Converted to Sale)'), ('RELEASED', 'Released (Cancelled Hold)')], db_index=True, default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional reservation expiration time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Central Distribution Hub'", max_length=150)),
                ('code', models.CharField(db_index=True, help_text="Unique code e.g. 'WH-CENTRAL-01'", max_length=50, unique=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('is_primary', models.BooleanField(default=False, help_text='Default warehouse for automated fulfillment routing')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Assigned warehouse supervisor or staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt (Inbound)'), ('SALE', 'Sale Deduction (Outbound)'), ('RETURN', 'Customer Return (Inbound)'), ('TRANSFER_IN', 'Warehouse Transfer In'), ('TRANSFER_OUT', 'Warehouse Transfer Out'), ('ADJUSTMENT_IN', 'Adjustment (Count Increase)'), ('ADJUSTMENT_OUT', 'Adjustment (Count Decrease)'), ('DAMAGE', 'Damaged Stock (Written Off)'), ('LOSS', 'Shrinkage / Lost'), ('RESERVATION', 'Stock Reserved for Order'), ('RESERVATION_RELEASE', 'Reservation Released'), ('CANCELLATION', 'Order Cancellation Restock')], db_index=True, max_length=30)),
                ('quantity', models.IntegerField(help_text='Signed quantity change (+10, -2)')),
                ('before_quantity', models.IntegerField(help_text='Physical on-hand quantity before movement')),
                ('after_quantity', models.IntegerField(help_text='Physical on-hand quantity after movement')),
                ('before_reserved', models.IntegerField(default=0, help_text='Reserved quantity before movement')),
                ('after_reserved', models.IntegerField(default=0, help_text='Reserved quantity after movement')),
                ('reference_type', models.CharField(blank=True, db_index=True, help_text="e.g. 'ORDER', 'ADJUSTMENT', 'TRANSFER'", max_length=50)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='e.g. Order ID, Invoice #, Transfer #', max_length=100)),
                ('reason', models.TextField(blank=True, help_text='Operational notes or justification')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.location')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_quantity__gte', 0)), name='stock_on_hand_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='stock_reserved_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('incoming_quantity__gte', 0)), name='stock_incoming_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'warehouse', 'location'), name='unique_stock_product_variant_location'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_warehouse_location_code'),
        ),
    ]
