# Generated by Django 5.2 on 2026-09-08 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Role title (e.g. 'Inventory Manager', 'CMS Editor')", max_length=100, unique=True)),
                ('code', models.SlugField(help_text='Unique code for internal role checks', max_length=80, unique=True)),
                ('description', models.TextField(blank=True, help_text='Scope and responsibilities of this role')),
                ('is_superadmin', models.BooleanField(default=False, help_text='Designates this role as having universal access to all departments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, help_text='Management departments accessible by staff with this role', related_name='roles', to='core.managementdepartment')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Django permissions associated with this role', related_name='management_roles', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Management Role',
                'verbose_name_plural': 'Management Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_management_staff', models.BooleanField(default=False, help_text='Allows user to authenticate into the /management/ portal')),
                ('job_title', models.CharField(blank=True, default='', help_text='Staff job title / designation', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_access', models.ManyToManyField(blank=True, help_text='Direct department access granted to this user (in addition to role access)', related_name='assigned_user_profiles', to='core.managementdepartment')),
                ('roles', models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='user_profiles', to='accounts.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile & Staff Access',
                'verbose_name_plural': 'User Profiles & Staff Access',
            },
        ),
    ]
