# Generated by Django 5.2 on 2026-09-08 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempt', models.CharField(blank=True, default='', help_text='Username attempted on login', max_length=150)),
                ('action', models.CharField(choices=[('login_success', 'Management Login Success'), ('login_failure', 'Management Login Failure'), ('logout', 'Management Logout'), ('dept_access', 'Department Access'), ('permission_denied', 'Permission Denied'), ('create', 'Resource Created'), ('update', 'Resource Updated'), ('delete', 'Resource Deleted'), ('admin_action', 'Administrative Action')], db_index=True, max_length=50)),
                ('department', models.CharField(blank=True, db_index=True, default='', help_text='Target department slug or name', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User involved in this event (null if unauthenticated or failed login)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit & Security Log',
                'verbose_name_plural': 'Audit & Security Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
