# Generated by Django 5.2 on 2026-09-29 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0005_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique internal payment tracking identifier (e.g. TXN-YYYYMMDD-XXXXX)', max_length=100, unique=True)),
                ('gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('COD', 'Cash on Delivery')], db_index=True, default='RAZORPAY', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount in currency unit (e.g. INR)', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending Verification'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=30)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, default='', help_text='Razorpay Order ID (order_...)', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, default='', help_text='Razorpay Payment ID (pay_...)', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', help_text='HMAC SHA256 Signature verified from Razorpay Checkout', max_length=255)),
                ('method', models.CharField(blank=True, default='', help_text='Payment instrument (upi, card, netbanking, wallet)', max_length=50)),
                ('bank', models.CharField(blank=True, default='', max_length=100)),
                ('wallet', models.CharField(blank=True, default='', max_length=100)),
                ('vpa', models.CharField(blank=True, default='', help_text='UPI Virtual Payment Address if method is UPI', max_length=100)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_description', models.TextField(blank=True, default='')),
                ('error_source', models.CharField(blank=True, default='', max_length=100)),
                ('error_step', models.CharField(blank=True, default='', max_length=100)),
                ('error_reason', models.CharField(blank=True, default='', max_length=100)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Complete JSON response payload from Razorpay')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(blank=True, help_text='Cart snapshot at initiation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='cart.cart')),
                ('order', models.ForeignKey(blank=True, help_text='Associated order once confirmed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
