# Generated by Django 5.2 on 2026-09-30 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer_notes',
            field=models.TextField(blank=True, default='', help_text='Customer delivery instructions'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Designated shipping address for order creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending Verification'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Payment Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=30),
        ),
    ]
