"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (root workspace or ecom directory)
try:
    from dotenv import load_dotenv
    for _env_candidate in [BASE_DIR.parent / '.env', BASE_DIR / '.env']:
        if _env_candidate.exists():
            load_dotenv(dotenv_path=_env_candidate)
            break
except ImportError:
    pass

# Add apps directory to sys.path
sys.path.insert(0, str(BASE_DIR / 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key_env = (os.environ.get('SECRET_KEY') or '').strip()
SECRET_KEY = _secret_key_env if _secret_key_env else 'django-insecure-*_5j)@e$pk-67i8v)@n)f3rtlxeb7*u$++^(y30*78y^#vv)+i'

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = (os.environ.get('DEBUG') or '').strip()
DEBUG = _debug_env.lower() in ('true', '1', 'yes') if _debug_env else False

_allowed_env = (os.environ.get('ALLOWED_HOSTS') or '').strip()
if _allowed_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['*']

for _default_host in ['.vercel.app', 'localhost', '127.0.0.1', '*']:
    if _default_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_default_host)

# CSRF Trusted Origins for Vercel deployment
_csrf_env = (os.environ.get('CSRF_TRUSTED_ORIGINS') or '').strip()
if _csrf_env:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_env.split(',') if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []

for _default_origin in [
    'https://*.vercel.app',
    'https://*.now.sh',
    'http://127.0.0.1',
    'http://localhost',
]:
    if _default_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_default_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Domain Applications
    'apps.accounts',
    'apps.catalog',
    'apps.inventory',
    'apps.search',
    'apps.cart',
    'apps.wishlist',
    'apps.checkout',
    'apps.payments',
    'apps.orders',
    'apps.shipping',
    'apps.fulfillment',
    'apps.promotions',
    'apps.reviews',
    'apps.notifications',
    'apps.recommendations',
    'apps.cms',
    'apps.analytics',
    'apps.support',
    'apps.audit',
    'apps.settings',
    'apps.core',
    'apps.assistant',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.middleware.UniversalSessionSecurityMiddleware',
]

# Universal Session Security & Cache Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

ROOT_URLCONF = 'ecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.cms.context_processors.cms_context',
                'apps.cart.context_processors.cart_context',
                'apps.wishlist.context_processors.wishlist_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom.wsgi.application'


DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.config(
                default=DATABASE_URL,
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    except ImportError:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # Serverless runtime detection (Vercel has read-only filesystem except /tmp)
    is_vercel = bool(os.environ.get('VERCEL') or os.environ.get('VERCEL_ENV'))
    db_path = BASE_DIR / 'db.sqlite3'
    if is_vercel:
        import shutil
        tmp_db = Path('/tmp/db.sqlite3')
        if not tmp_db.exists():
            candidates = [
                BASE_DIR / 'db.sqlite3',
                BASE_DIR.parent / 'ecom' / 'db.sqlite3',
                BASE_DIR.parent / 'db.sqlite3',
                Path('/var/task/ecom/db.sqlite3'),
                Path('/var/task/db.sqlite3'),
            ]
            for src in candidates:
                if src.exists() and src.stat().st_size > 0:
                    try:
                        shutil.copy2(src, tmp_db)
                        break
                    except Exception:
                        pass
        db_path = tmp_db

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR.parent / 'staticfiles'
WHITENOISE_USE_FINDERS = True

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication & Administration Redirect Settings
LOGIN_URL = '/management/login/'
LOGIN_REDIRECT_URL = '/management/dashboard/'
LOGOUT_REDIRECT_URL = '/management/'

# ==============================================================================
# Session & Cookie Security Configuration
# Expire session on browser close & secure session handling
# ==============================================================================
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# ==============================================================================
# Google Gemini AI Assistant Settings (Strictly from environment variables)
# ==============================================================================
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-2.5-flash')

# Cache configuration for Rate Limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'cartivo-cache',
    }
}

