# Generated by Django 5.2 on 2026-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User-facing department name (e.g. 'Inventory Management')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL slug identifier (e.g. 'inventory')", max_length=80, unique=True)),
                ('code', models.CharField(help_text="Internal code namespace (e.g. 'inventory')", max_length=50, unique=True)),
                ('description', models.TextField(help_text='Short description displayed on the management card')),
                ('icon', models.CharField(default='layers', help_text="Lucide icon name (e.g. 'package', 'users', 'shopping-cart')", max_length=60)),
                ('url_name', models.CharField(blank=True, default='', help_text='Target URL or named route if customized', max_length=150)),
                ('required_permission', models.CharField(blank=True, default='', help_text="Optional permission codename required for access (e.g. 'inventory.view_inventory')", max_length=100)),
                ('login_required', models.BooleanField(default=True, help_text='Require authentication to access this department')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this department is visible and accessible')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ordering rank on the management portal grid')),
                ('accent_color', models.CharField(default='blue', help_text='Theme color identifier: blue, emerald, amber, purple, rose, indigo, slate, cyan', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Management Department',
                'verbose_name_plural': 'Management Departments',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
