# Generated by Django 5.2 on 2026-09-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_index=True, help_text="Unique department login identifier (e.g. 'CMS001', 'INV001')", max_length=50, unique=True)),
                ('password_hash', models.CharField(help_text='Securely hashed password (never stored in plaintext)', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], db_index=True, default='PENDING', help_text='Operational access state of the department account', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful department authentication', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(help_text='Target management department associated with this account', on_delete=django.db.models.deletion.CASCADE, related_name='account', to='core.managementdepartment')),
            ],
            options={
                'verbose_name': 'Department Account',
                'verbose_name_plural': 'Department Accounts',
                'ordering': ['department__display_order', 'department__name'],
            },
        ),
    ]
