# Generated by Django 5.2 on 2026-09-16 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departmentaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentaccount',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked Django User of the project for auth-based login and permissions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
